In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd

In [13]:
df = gpd.read_file('puntos_emergencias.gpkg', driver='GPKG')
df

c:\Users\ptole\miniforge3\envs\geo312\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: driver GPKG does not support open option DRIVER
  return ogr_read(

,Fecha,Texto,FECHA_DIA,FECHA_HORA,CODIGO_EMERGENCIA,URL,CODIGO_UNIDAD,FECHA_DT,MONTH_NAME,DAY,DAY_NAME,FECHA_HORA_NUM,CATEGORIA_EMERGENCIA,latitud_x,longitud_y,utm_x_32718,utm_y_32718,geometry
0,2022-01-04T14:06:48.000Z,EMERGENCIA: 11:06 10-8 (LLAMADO NO CLASIFICADO...,2022-01-04,14:06:48,10-8,None,B-1,2022-01-04 14:06:48+00:00,January,4,Tuesday,14,LLAMADOS SIN SUBCLASIFICACIÓN,NaN,NaN,NaN,NaN,POINT EMPTY
1,2022-01-04T16:04:42.000Z,"EMERGENCIA: 13:04 10-4 (RESCATE VEHICULAR), AV...",2022-01-04,16:04:42,10-4,None,"RB-5, B-9",2022-01-04 16:04:42+00:00,January,4,Tuesday,16,RESCATE VEHICULAR,NaN,NaN,NaN,NaN,POINT EMPTY
2,2022-01-04T17:40:50.000Z,EMERGENCIA: 14:40 10-2 (LLAMADO DE PASTIZALES)...,2022-01-04,17:40:50,10-2,None,B-4,2022-01-04 17:40:50+00:00,January,4,Tuesday,17,INCENDIO PASTIZAL O FORESTAL,NaN,NaN,NaN,NaN,POINT EMPTY
3,2022-01-04T17:43:44.000Z,"14:43, SALE B-11 A 10-2 (LLAMADO DE PASTIZALE...",2022-01-04,17:43:44,10-2,None,B-11,2022-01-04 17:43:44+00:00,January,4,Tuesday,17,INCENDIO PASTIZAL O FORESTAL,NaN,NaN,NaN,NaN,POINT EMPTY
4,2022-01-04T17:45:44.000Z,"14:45, SALE F-7 A 10-2 (LLAMADO DE PASTIZALES...",2022-01-04,17:45:44,10-2,None,F-7,2022-01-04 17:45:44+00:00,January,4,Tuesday,17,INCENDIO PASTIZAL O FORESTAL,NaN,NaN,NaN,NaN,POINT EMPTY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489,2026-04-16T17:39:45.000Z,10-4-1 AVENIDA ARGENTINA / JUAN DE LA CRUZ TAP...,2026-04-16,17:39:45,10-4-1,https://t.co/usdpl9cnYL,"RB-3, BQ-7",2026-04-16 17:39:45+00:00,April,16,Thursday,17,RESCATE VEHICULAR,-36.721710,-73.122432,667674.079374,5.934355e+06,POINT (667674.079 5934355.435)
10490,2026-04-16T17:46:30.000Z,SALE RB-6 A 10-4-1 AVENIDA ARGENTINA / JUAN DE...,2026-04-16,17:46:30,10-4-1,https://t.co/usdpl9cnYL,RB-6,2026-04-16 17:46:30+00:00,April,16,Thursday,17,RESCATE VEHICULAR,-36.721710,-73.122432,667674.079374,5.934355e+06,POINT (667674.079 5934355.435)
10491,2026-04-16T17:49:42.000Z,SALE RX-5 A 10-4-1 AVENIDA ARGENTINA / JUAN DE...,2026-04-16,17:49:42,10-4-1,https://t.co/usdpl9cnYL,RX-5,2026-04-16 17:49:42+00:00,April,16,Thursday,17,RESCATE VEHICULAR,-36.721710,-73.122432,667674.079374,5.934355e+06,POINT (667674.079 5934355.435)
10492,2026-04-16T23:19:32.000Z,10-3-4 PORTALES / HUALPEN RB-3 https://t.co/XL...,2026-04-16,23:19:32,10-3-4,https://t.co/XLloen6rGy,RB-3,2026-04-16 23:19:32+00:00,April,16,Thursday,23,RESCATE DE PERSONAS,-36.733166,-73.111053,668665.316723,5.933065e+06,POINT (668665.317 5933064.529)
10493,2026-04-17T00:07:14.000Z,10-3-4 PORTALES / HUALPÉN RB-3 https://t.co/IO...,2026-04-17,00:07:14,10-3-4,https://t.co/IOvGsTFACn,RB-3,2026-04-17 00:07:14+00:00,April,17,Friday,0,RESCATE DE PERSONAS,-36.733210,-73.111094,668661.549551,5.933060e+06,POINT (668661.55 5933059.687)

In [14]:
df = df[df['latitud_x'].notnull()]
df

,Fecha,Texto,FECHA_DIA,FECHA_HORA,CODIGO_EMERGENCIA,URL,CODIGO_UNIDAD,FECHA_DT,MONTH_NAME,DAY,DAY_NAME,FECHA_HORA_NUM,CATEGORIA_EMERGENCIA,latitud_x,longitud_y,utm_x_32718,utm_y_32718,geometry
4427,2023-07-13T14:27:25.000Z,10-3-4: Estamos respondiendo a un rescate de p...,2023-07-13,14:27:25,10-3-4,https://t.co/xoXMuRi2PT,RB5,2023-07-13 14:27:25+00:00,July,13,Thursday,14,RESCATE DE PERSONAS,-36.781947,-73.074838,671790.476623,5.927588e+06,POINT (671790.477 5927588.015)
4428,2023-07-13T22:04:25.000Z,10-4-1: Estamos respondiendo a un rescate vehi...,2023-07-13,22:04:25,10-4-1,https://t.co/dCGKtw1ovA,"RB3, B11, RB5",2023-07-13 22:04:25+00:00,July,13,Thursday,22,RESCATE VEHICULAR,-36.740562,-73.119067,667933.560927,5.932258e+06,POINT (667933.561 5932257.997)
4429,2023-07-14T14:39:40.000Z,10-0-4: Estamos respondiendo a una emergencia ...,2023-07-14,14:39:40,10-0-4,https://t.co/SM9WODEoXs,"B3, BR01, B4, F7",2023-07-14 14:39:40+00:00,July,14,Friday,14,INCENDIO ESTRUCTURAL,-36.717953,-73.130163,666991.733677,5.934786e+06,POINT (666991.734 5934785.852)
4430,2023-07-14T14:41:59.000Z,10-0-4: Estamos respondiendo a un Incendio est...,2023-07-14,14:41:59,10-0-4,https://t.co/SM9WODEoXs,"B3, BR01, B4, F7, RB6",2023-07-14 14:41:59+00:00,July,14,Friday,14,INCENDIO ESTRUCTURAL,-36.717953,-73.130163,666991.733677,5.934786e+06,POINT (666991.734 5934785.852)
4431,2023-07-14T14:50:03.000Z,Alarma de Incendio: Estamos respondiendo a INC...,2023-07-14,14:50:03,10-0-6,https://t.co/SM9WODEoXs,"B3, BR01, B4, F7, RB6, B5, B9, BM2, H8",2023-07-14 14:50:03+00:00,July,14,Friday,14,INCENDIO ESTRUCTURAL,-36.717953,-73.130163,666991.733677,5.934786e+06,POINT (666991.734 5934785.852)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489,2026-04-16T17:39:45.000Z,10-4-1 AVENIDA ARGENTINA / JUAN DE LA CRUZ TAP...,2026-04-16,17:39:45,10-4-1,https://t.co/usdpl9cnYL,"RB-3, BQ-7",2026-04-16 17:39:45+00:00,April,16,Thursday,17,RESCATE VEHICULAR,-36.721710,-73.122432,667674.079374,5.934355e+06,POINT (667674.079 5934355.435)
10490,2026-04-16T17:46:30.000Z,SALE RB-6 A 10-4-1 AVENIDA ARGENTINA / JUAN DE...,2026-04-16,17:46:30,10-4-1,https://t.co/usdpl9cnYL,RB-6,2026-04-16 17:46:30+00:00,April,16,Thursday,17,RESCATE VEHICULAR,-36.721710,-73.122432,667674.079374,5.934355e+06,POINT (667674.079 5934355.435)
10491,2026-04-16T17:49:42.000Z,SALE RX-5 A 10-4-1 AVENIDA ARGENTINA / JUAN DE...,2026-04-16,17:49:42,10-4-1,https://t.co/usdpl9cnYL,RX-5,2026-04-16 17:49:42+00:00,April,16,Thursday,17,RESCATE VEHICULAR,-36.721710,-73.122432,667674.079374,5.934355e+06,POINT (667674.079 5934355.435)
10492,2026-04-16T23:19:32.000Z,10-3-4 PORTALES / HUALPEN RB-3 https://t.co/XL...,2026-04-16,23:19:32,10-3-4,https://t.co/XLloen6rGy,RB-3,2026-04-16 23:19:32+00:00,April,16,Thursday,23,RESCATE DE PERSONAS,-36.733166,-73.111053,668665.316723,5.933065e+06,POINT (668665.317 5933064.529)
10493,2026-04-17T00:07:14.000Z,10-3-4 PORTALES / HUALPÉN RB-3 https://t.co/IO...,2026-04-17,00:07:14,10-3-4,https://t.co/IOvGsTFACn,RB-3,2026-04-17 00:07:14+00:00,April,17,Friday,0,RESCATE DE PERSONAS,-36.733210,-73.111094,668661.549551,5.933060e+06,POINT (668661.55 5933059.687)

In [32]:
from sklearn.cluster import KMeans
import numpy as np

eventos = df[['utm_x_32718', 'utm_y_32718']].copy()
eventos['evento'] = 'ev_' + eventos.index.astype(str)
eventos.columns = ['ex', 'ey', 'evento']
coords = eventos[['ex', 'ey']].copy().to_numpy()
dmax = 120
stat = []

for k in range(100, 10_000+1):
    model = KMeans(n_clusters=k, random_state=42)
    labels = model.fit_predict(coords)
    ev = eventos.copy()
    ev['k'] = 'k_' + labels.astype(str)
    cides = pd.DataFrame(model.cluster_centers_, columns=['cx', 'cy'])
    cides['k'] = 'k_' + cides.index.astype(str)
    ctoe = pd.merge(cides, ev, on='k', how='inner')
    ctoe['dist'] = np.sqrt((ctoe['cx'] - ctoe['ex'])**2 + (ctoe['cy'] - ctoe['ey'])**2)
    max_dist = ctoe['dist'].max()

    ctoe['ev_in_k'] = ctoe.groupby('k')['evento'].transform('count')

    print(f'k={k}, max_dist={max_dist}, ev_in_k={ctoe["ev_in_k"].max()}, {ctoe["ev_in_k"].mean()}')
    stat.append({'k': k, 'max_dist': max_dist, 'ev_in_k_max': ctoe['ev_in_k'].max(), 'ev_in_k_mean': ctoe['ev_in_k'].mean()})

    if max_dist < dmax:
        break

k=100, max_dist=2844.3981688243794, ev_in_k=282, 113.63336630398945
k=101, max_dist=2844.3981688243794, ev_in_k=282, 112.01516650181338
k=102, max_dist=2844.3981688243794, ev_in_k=282, 109.2809099901088
k=103, max_dist=2844.3981688243794, ev_in_k=282, 109.25123639960435
k=104, max_dist=2844.3981688243794, ev_in_k=282, 107.01615562149686
k=105, max_dist=2844.3981688243794, ev_in_k=282, 105.99703264094956
k=106, max_dist=2844.3981688243794, ev_in_k=282, 106.92614573030004
k=107, max_dist=1954.9309293910665, ev_in_k=282, 106.92350807781075
k=108, max_dist=1954.9309293910665, ev_in_k=282, 104.63633366303989
k=109, max_dist=1954.9309293910665, ev_in_k=190, 99.03395977579954
k=110, max_dist=1954.9309293910665, ev_in_k=190, 98.97560171447412
k=111, max_dist=1954.9309293910665, ev_in_k=190, 97.70689086712825
k=112, max_dist=1954.9309293910665, ev_in_k=190, 96.65875370919882
k=113, max_dist=1954.9309293910665, ev_in_k=190, 95.51104516979888
k=114, max_dist=1954.9309293910665, ev_in_k=190, 95.45268710847346
k=115, max_dist=1954.9309293910665, ev_in_k=190, 95.39136168809759
k=116, max_dist=1954.9309293910665, ev_in_k=190, 94.67688757006265
k=117, max_dist=1954.9309293910665, ev_in_k=190, 94.12924497197494
k=118, max_dist=1954.9309293910665, ev_in_k=190, 93.9891196834817
k=119, max_dist=1954.9309293910665, ev_in_k=190, 93.98648203099242
k=120, max_dist=1954.9309293910665, ev_in_k=190, 93.26640290141773
k=121, max_dist=1954.9309293910665, ev_in_k=190, 93.1905703923508
k=122, max_dist=1954.9309293910665, ev_in_k=190, 92.69502143092647
k=123, max_dist=1954.9309293910665, ev_in_k=190, 92.62446422683811
k=124, max_dist=1954.9309293910665, ev_in_k=190, 92.62182657434883
k=125, max_dist=1954.9309293910665, ev_in_k=190, 90.82261787009561
k=126, max_dist=1954.9309293910665, ev_in_k=189, 89.50675898450379
k=127, max_dist=1954.9309293910665, ev_in_k=189, 89.00956149027365
k=128, max_dist=1954.9309293910665, ev_in_k=189, 89.00758325090669
k=129, max_dist=1954.9309293910665, ev_in_k=189, 88.07715133531157
k=130, max_dist=1954.9309293910665, ev_in_k=190, 86.68710847345862
k=131, max_dist=1954.9309293910665, ev_in_k=190, 85.88822947576656
k=132, max_dist=1954.9309293910665, ev_in_k=190, 85.87504121332015
k=133, max_dist=1954.9309293910665, ev_in_k=190, 83.1823277283218
k=134, max_dist=1954.9309293910665, ev_in_k=190, 82.6129244971975
k=135, max_dist=1954.9309293910665, ev_in_k=190, 82.37751401252885
k=136, max_dist=1954.9309293910665, ev_in_k=190, 81.79393339927465
k=137, max_dist=1954.9309293910665, ev_in_k=190, 81.40092317837124
k=138, max_dist=1954.9309293910665, ev_in_k=190, 80.45004945598417
k=139, max_dist=1954.9309293910665, ev_in_k=190, 79.52291460600065
k=140, max_dist=1954.9309293910665, ev_in_k=190, 79.49455984174085
k=141, max_dist=1954.9309293910665, ev_in_k=190, 78.42202439828553
k=142, max_dist=1954.9309293910665, ev_in_k=190, 77.80844048796571
k=143, max_dist=1954.9309293910665, ev_in_k=190, 77.03758654797231
k=144, max_dist=1274.2453301357862, ev_in_k=190, 77.03560830860535
k=145, max_dist=1274.2453301357862, ev_in_k=190, 76.98977909660402
k=146, max_dist=1274.2453301357862, ev_in_k=190, 76.42828882294758
k=147, max_dist=1274.2453301357862, ev_in_k=190, 75.96043521266073
k=148, max_dist=1274.2453301357862, ev_in_k=190, 75.6178700956149
k=149, max_dist=1493.0494896148741, ev_in_k=219, 75.93076162215628
k=150, max_dist=1691.7579021205574, ev_in_k=219, 75.46521595779755
k=151, max_dist=1691.7579021205574, ev_in_k=214, 75.11275964391692
k=152, max_dist=1691.7579021205574, ev_in_k=214, 74.40059347181008
k=153, max_dist=1691.7579021205574, ev_in_k=214, 73.08341575997362
k=154, max_dist=1691.7579021205574, ev_in_k=153, 69.91031981536433
k=155, max_dist=1691.7579021205574, ev_in_k=153, 69.48532805802836
k=156, max_dist=1691.7579021205574, ev_in_k=153, 68.47543686119354
k=157, max_dist=1691.7579021205574, ev_in_k=153, 68.1856247939334
k=158, max_dist=1691.7579021205574, ev_in_k=153, 67.60270359380152
k=159, max_dist=1771.9299597061065, ev_in_k=153, 67.56742499175733
k=160, max_dist=1771.9299597061065, ev_in_k=153, 67.38081107814045
k=161, max_dist=1553.4507395600626, ev_in_k=153, 67.33728981206725
k=162, max_dist=1553.4507395600626, ev_in_k=153, 67.31091328717442
k=163, max_dist=1450.7150630215713, ev_in_k=153, 67.29212001318827
k=164, max_dist=1450.7150630215713, ev_in_k=153, 66.32805802835476
k=165, max_dist=1450.7150630215713, ev_in_k=153, 65.53808110781405
k=166, max_dist=1450.7150630215713, ev_in_k=153, 65.32739861523244
k=167, max_dist=1450.7150630215713, ev_in_k=161, 65.22387075502803
k=168, max_dist=1450.7150630215713, ev_in_k=161, 65.21364985163204
k=169, max_dist=1450.7150630215713, ev_in_k=151, 64.27365644576327
k=170, max_dist=1450.7150630215713, ev_in_k=151, 64.11242993735576
k=171, max_dist=1450.7150630215713, ev_in_k=151, 64.04253214638972
k=172, max_dist=1450.7150630215713, ev_in_k=151, 63.41411144081767
k=173, max_dist=1450.7150630215713, ev_in_k=151, 63.0016485328058
k=174, max_dist=1450.7150630215713, ev_in_k=151, 62.859215298384434
k=175, max_dist=1450.7150630215713, ev_in_k=151, 62.519617540389056
k=176, max_dist=1450.7150630215713, ev_in_k=151, 62.40191229805473
k=177, max_dist=1450.7150630215713, ev_in_k=151, 62.1730959446093
k=178, max_dist=1450.7150630215713, ev_in_k=151, 62.16485328058028
k=179, max_dist=1127.3326288676274, ev_in_k=151, 62.15891856247939
k=180, max_dist=1127.3326288676274, ev_in_k=151, 62.12759643916914
k=181, max_dist=1127.3326288676274, ev_in_k=151, 61.653808110781405
k=182, max_dist=1127.3326288676274, ev_in_k=151, 61.20705572040884
k=183, max_dist=1127.3326288676274, ev_in_k=151, 61.18100890207715
k=184, max_dist=1127.3326288676274, ev_in_k=151, 61.16815034619189
k=185, max_dist=973.4164017618945, ev_in_k=151, 61.16254533465216
k=186, max_dist=973.4164017618945, ev_in_k=151, 61.16188592152984
k=187, max_dist=973.4164017618945, ev_in_k=151, 60.211671612265086
k=188, max_dist=973.4164017618945, ev_in_k=151, 59.99142762940983
k=189, max_dist=973.4164017618945, ev_in_k=151, 59.82294757665677
k=190, max_dist=973.4164017618945, ev_in_k=151, 59.88064622485987
k=191, max_dist=973.4164017618945, ev_in_k=151, 59.232113419057036
k=192, max_dist=973.4164017618945, ev_in_k=151, 59.03527860204418
k=193, max_dist=973.4164017618945, ev_in_k=151, 58.80844048796571
k=194, max_dist=973.4164017618945, ev_in_k=151, 58.310583580613255
k=195, max_dist=973.4164017618945, ev_in_k=151, 57.79063633366304
k=196, max_dist=973.4164017618945, ev_in_k=151, 57.78667985492911
k=197, max_dist=973.4164017618945, ev_in_k=151, 57.64556544675239
k=198, max_dist=973.4164017618945, ev_in_k=151, 57.63369601055061
k=199, max_dist=973.4164017618945, ev_in_k=151, 57.11671612265084
k=200, max_dist=973.4164017618945, ev_in_k=151, 56.8160237388724
k=201, max_dist=973.4164017618945, ev_in_k=151, 55.03692713484998
k=202, max_dist=973.4164017618945, ev_in_k=151, 54.90867128255852
k=203, max_dist=973.4164017618945, ev_in_k=151, 54.724035608308604
k=204, max_dist=755.036074820202, ev_in_k=151, 54.70623145400594
k=205, max_dist=755.036074820202, ev_in_k=151, 54.69765908341576
k=206, max_dist=755.036074820202, ev_in_k=151, 54.131223211341904
k=207, max_dist=755.036074820202, ev_in_k=151, 53.688757006264424
k=208, max_dist=755.036074820202, ev_in_k=151, 53.47082096933729
k=209, max_dist=755.036074820202, ev_in_k=151, 53.21628750412133
k=210, max_dist=755.036074820202, ev_in_k=151, 52.93768545994065
k=211, max_dist=755.036074820202, ev_in_k=151, 51.88592152983844
k=212, max_dist=755.036074820202, ev_in_k=151, 51.65842400263765
k=213, max_dist=755.036074820202, ev_in_k=151, 51.518958127266735
k=214, max_dist=742.1833439955068, ev_in_k=151, 51.44114737883284
k=215, max_dist=742.1833439955068, ev_in_k=151, 51.14243323442137
k=216, max_dist=742.1833439955068, ev_in_k=151, 51.132542037586546
k=217, max_dist=742.1833439955068, ev_in_k=151, 50.695351137487634
k=218, max_dist=742.1833439955068, ev_in_k=151, 50.603692713484996
k=219, max_dist=742.1833439955068, ev_in_k=151, 50.59775799538411
k=220, max_dist=742.1833439955068, ev_in_k=151, 50.25486317177712
k=221, max_dist=742.1833439955068, ev_in_k=151, 50.06495219254863
k=222, max_dist=742.1833439955068, ev_in_k=151, 49.810089020771514
k=223, max_dist=742.1833439955068, ev_in_k=151, 49.532805802835476
k=224, max_dist=742.1833439955068, ev_in_k=151, 49.532146389713155
k=225, max_dist=742.1833439955068, ev_in_k=151, 49.47873392680514
k=226, max_dist=742.1833439955068, ev_in_k=151, 49.317177711836464
k=227, max_dist=742.1833439955068, ev_in_k=151, 49.182987141444116
k=228, max_dist=742.1833439955068, ev_in_k=151, 49.182657434882955
k=229, max_dist=742.1833439955068, ev_in_k=151, 48.75173095944609
k=230, max_dist=742.1833439955068, ev_in_k=151, 48.70952851961754
k=231, max_dist=742.1833439955068, ev_in_k=151, 48.4447741510056
k=232, max_dist=742.1833439955068, ev_in_k=151, 48.131552917903065
k=233, max_dist=742.1833439955068, ev_in_k=151, 48.044840092317834
k=234, max_dist=742.1833439955068, ev_in_k=151, 47.52357401912298
k=235, max_dist=742.1833439955068, ev_in_k=151, 47.45895153313551
k=236, max_dist=742.1833439955068, ev_in_k=103, 45.4849983514672
k=237, max_dist=742.1833439955068, ev_in_k=103, 45.368282228816355
k=238, max_dist=742.1833439955068, ev_in_k=103, 45.23013517969007
k=239, max_dist=742.1833439955068, ev_in_k=103, 45.19090009891197
k=240, max_dist=742.1833439955068, ev_in_k=103, 45.188262446422684
k=241, max_dist=742.1833439955068, ev_in_k=103, 44.95878667985493
k=242, max_dist=742.1833439955068, ev_in_k=103, 44.75799538410814
k=243, max_dist=742.1833439955068, ev_in_k=103, 44.28618529508737
k=244, max_dist=742.1833439955068, ev_in_k=103, 44.25881965051104
k=245, max_dist=742.1833439955068, ev_in_k=103, 44.253544345532475
k=246, max_dist=742.1833439955068, ev_in_k=103, 44.20738542697
k=247, max_dist=742.1833439955068, ev_in_k=103, 44.19057039235081
k=248, max_dist=742.1833439955068, ev_in_k=103, 44.182327728321795
k=249, max_dist=742.1833439955068, ev_in_k=103, 44.181668315199474
k=250, max_dist=742.1833439955068, ev_in_k=103, 43.72700296735905
k=251, max_dist=742.1833439955068, ev_in_k=103, 43.47213979558193
k=252, max_dist=742.1833439955068, ev_in_k=103, 43.45895153313551
k=253, max_dist=742.1833439955068, ev_in_k=103, 43.09990108803165
k=254, max_dist=742.1833439955068, ev_in_k=103, 42.94263105835806
k=255, max_dist=742.1833439955068, ev_in_k=103, 42.80877019452687
k=256, max_dist=742.1833439955068, ev_in_k=103, 42.71414441147379
k=257, max_dist=742.1833439955068, ev_in_k=103, 42.65776458951533
k=258, max_dist=742.1833439955068, ev_in_k=103, 42.59215298384438
k=259, max_dist=742.1833439955068, ev_in_k=103, 42.40092317837125
k=260, max_dist=742.1833439955068, ev_in_k=103, 42.29277942631058
k=261, max_dist=742.1833439955068, ev_in_k=103, 42.160237388724035
k=262, max_dist=742.1833439955068, ev_in_k=103, 41.481371579294425
k=263, max_dist=742.1833439955068, ev_in_k=103, 40.788987800857235
k=264, max_dist=742.1833439955068, ev_in_k=103, 40.525552258489945
k=265, max_dist=742.1833439955068, ev_in_k=103, 40.5242334322453
k=266, max_dist=742.1833439955068, ev_in_k=103, 40.26442466205077
k=267, max_dist=742.1833439955068, ev_in_k=103, 40.024727992087044
k=268, max_dist=742.1833439955068, ev_in_k=103, 40.017804154302674
k=269, max_dist=742.1833439955068, ev_in_k=103, 39.76722716782064
k=270, max_dist=742.1833439955068, ev_in_k=103, 39.62149686778767
k=271, max_dist=742.1833439955068, ev_in_k=103, 39.554236729310915
k=272, max_dist=742.1833439955068, ev_in_k=103, 39.39004286185295
k=273, max_dist=742.1833439955068, ev_in_k=103, 39.27992087042532
k=274, max_dist=742.1833439955068, ev_in_k=103, 39.01121002307946
k=275, max_dist=742.1833439955068, ev_in_k=103, 38.82921200131883
k=276, max_dist=742.1833439955068, ev_in_k=103, 38.824266402901415
k=277, max_dist=742.1833439955068, ev_in_k=103, 38.82195845697329
k=278, max_dist=742.1833439955068, ev_in_k=103, 38.740850642927796
k=279, max_dist=742.1833439955068, ev_in_k=103, 38.573689416419384
k=280, max_dist=742.1833439955068, ev_in_k=103, 38.49093306956809
k=281, max_dist=742.1833439955068, ev_in_k=103, 38.08638311902407
k=282, max_dist=742.1833439955068, ev_in_k=103, 37.961424332344215
k=283, max_dist=742.1833439955068, ev_in_k=103, 37.960435212660734
k=284, max_dist=646.5340592551385, ev_in_k=103, 37.95779756017145
k=285, max_dist=646.5340592551385, ev_in_k=103, 37.74282888229476
k=286, max_dist=646.5340592551385, ev_in_k=103, 37.59314210352786
k=287, max_dist=646.5340592551385, ev_in_k=103, 37.35773161885921
k=288, max_dist=646.5340592551385, ev_in_k=103, 37.30563798219585
k=289, max_dist=646.5340592551385, ev_in_k=103, 36.79063633366304
k=290, max_dist=646.5340592551385, ev_in_k=103, 36.69831849653808
k=291, max_dist=646.5340592551385, ev_in_k=103, 36.53775140125288
k=292, max_dist=646.5340592551385, ev_in_k=103, 36.518298714144414
k=293, max_dist=646.5340592551385, ev_in_k=103, 36.445763270689085
k=294, max_dist=646.5340592551385, ev_in_k=103, 36.34256511704583
k=295, max_dist=646.5340592551385, ev_in_k=103, 36.138147049126275
k=296, max_dist=646.5340592551385, ev_in_k=103, 36.083415759973626
k=297, max_dist=646.5340592551385, ev_in_k=103, 35.938674579624134
k=298, max_dist=646.5340592551385, ev_in_k=103, 35.83679525222552
k=299, max_dist=646.5340592551385, ev_in_k=103, 35.79063633366304
k=300, max_dist=646.5340592551385, ev_in_k=103, 35.74315858885592
k=301, max_dist=646.5340592551385, ev_in_k=103, 35.74118034948896
k=302, max_dist=646.5340592551385, ev_in_k=103, 35.59215298384438
k=303, max_dist=646.5340592551385, ev_in_k=103, 35.5334652159578
k=304, max_dist=646.5340592551385, ev_in_k=103, 35.47642598087702
k=305, max_dist=646.5340592551385, ev_in_k=103, 35.282228816353445
k=306, max_dist=646.5340592551385, ev_in_k=103, 35.17441477085394
k=307, max_dist=646.5340592551385, ev_in_k=103, 35.16254533465216
k=308, max_dist=646.5340592551385, ev_in_k=103, 35.08572370590175
k=309, max_dist=646.5340592551385, ev_in_k=103, 34.9874711506759
k=310, max_dist=646.5340592551385, ev_in_k=103, 34.96274315858886
k=311, max_dist=646.5340592551385, ev_in_k=103, 34.85097263435542
k=312, max_dist=646.5340592551385, ev_in_k=103, 34.78602044180679
k=313, max_dist=646.5340592551385, ev_in_k=103, 34.75173095944609
k=314, max_dist=646.5340592551385, ev_in_k=103, 34.68051434223541
k=315, max_dist=646.5340592551385, ev_in_k=103, 34.67787668974613
k=316, max_dist=646.5340592551385, ev_in_k=103, 34.61688097593142
k=317, max_dist=646.5340592551385, ev_in_k=103, 34.56544675239037
k=318, max_dist=646.5340592551385, ev_in_k=103, 34.439169139465875
k=319, max_dist=646.5340592551385, ev_in_k=103, 34.346191889218595
k=320, max_dist=646.5340592551385, ev_in_k=103, 34.2324431256182
k=321, max_dist=646.5340592551385, ev_in_k=103, 34.09792284866469
k=322, max_dist=646.5340592551385, ev_in_k=103, 34.01318826244642
k=323, max_dist=646.5340592551385, ev_in_k=103, 34.009561490273654
k=324, max_dist=646.5340592551385, ev_in_k=103, 33.868447082096935
k=325, max_dist=646.5340592551385, ev_in_k=103, 33.794922518958124
k=326, max_dist=646.5340592551385, ev_in_k=103, 33.77909660402242
k=327, max_dist=646.5340592551385, ev_in_k=92, 33.102538740520934
k=328, max_dist=646.5340592551385, ev_in_k=92, 33.00725354434553
k=329, max_dist=646.5340592551385, ev_in_k=92, 33.00659413122321
k=330, max_dist=646.5340592551385, ev_in_k=92, 33.002967359050444
k=331, max_dist=646.5340592551385, ev_in_k=92, 32.91559512034289
k=332, max_dist=646.5340592551385, ev_in_k=92, 32.72964061984833
k=333, max_dist=646.5340592551385, ev_in_k=92, 32.69403231124299
k=334, max_dist=646.5340592551385, ev_in_k=92, 32.63600395647873
k=335, max_dist=646.5340592551385, ev_in_k=92, 32.58819650511045
k=336, max_dist=646.5340592551385, ev_in_k=92, 32.582921200131885
k=337, max_dist=646.5340592551385, ev_in_k=92, 32.5334652159578
k=338, max_dist=646.5340592551385, ev_in_k=92, 32.53313550939664
k=339, max_dist=646.5340592551385, ev_in_k=92, 32.340257171117706
k=340, max_dist=646.5340592551385, ev_in_k=92, 32.20013188262446
k=341, max_dist=646.5340592551385, ev_in_k=92, 32.19914276294098
k=342, max_dist=646.5340592551385, ev_in_k=92, 32.19881305637982
k=343, max_dist=646.5340592551385, ev_in_k=92, 32.15661061655127
k=344, max_dist=646.5340592551385, ev_in_k=92, 31.98977909660402
k=345, max_dist=646.5340592551385, ev_in_k=92, 31.932410154962085
k=346, max_dist=646.5340592551385, ev_in_k=92, 31.629739531816682
k=347, max_dist=646.5340592551385, ev_in_k=92, 31.456973293768545
k=348, max_dist=646.5340592551385, ev_in_k=87, 31.328387734915925
k=349, max_dist=646.5340592551385, ev_in_k=87, 31.323771843059678
k=350, max_dist=646.5340592551385, ev_in_k=87, 31.240356083086052
k=351, max_dist=646.5340592551385, ev_in_k=87, 31.206396307286514
k=352, max_dist=646.5340592551385, ev_in_k=87, 31.136168809759315
k=353, max_dist=646.5340592551385, ev_in_k=87, 31.06528189910979
k=354, max_dist=646.5340592551385, ev_in_k=87, 31.06495219254863
k=355, max_dist=646.5340592551385, ev_in_k=87, 31.049785690735245
k=356, max_dist=587.1803179440401, ev_in_k=87, 31.048466864490603
k=357, max_dist=587.1803179440401, ev_in_k=87, 31.01846356742499
k=358, max_dist=587.1803179440401, ev_in_k=87, 31.004286185295086
k=359, max_dist=587.1803179440401, ev_in_k=87, 31.002967359050444
k=360, max_dist=587.1803179440401, ev_in_k=87, 31.002307945928123
k=361, max_dist=587.1803179440401, ev_in_k=87, 30.864490603363006
k=362, max_dist=587.1803179440401, ev_in_k=87, 30.690735245631387
k=363, max_dist=587.1803179440401, ev_in_k=87, 30.392021101219914
k=364, max_dist=587.1803179440401, ev_in_k=87, 30.391031981536432
k=365, max_dist=587.1803179440401, ev_in_k=87, 30.35047807451368
k=366, max_dist=587.1803179440401, ev_in_k=87, 30.324431256182
k=367, max_dist=587.1803179440401, ev_in_k=87, 30.323442136498517
k=368, max_dist=587.1803179440401, ev_in_k=87, 30.316848005275304
k=369, max_dist=587.1803179440401, ev_in_k=87, 30.315858885591823
k=370, max_dist=550.3376496506875, ev_in_k=87, 30.298384437850313
k=371, max_dist=550.3376496506875, ev_in_k=87, 30.032970656116056
k=372, max_dist=550.3376496506875, ev_in_k=87, 29.995384108143753
k=373, max_dist=550.3376496506875, ev_in_k=87, 29.89614243323442
k=374, max_dist=550.3376496506875, ev_in_k=87, 29.881635344543355
k=375, max_dist=550.3376496506875, ev_in_k=87, 29.865150016485327
k=376, max_dist=550.3376496506875, ev_in_k=87, 29.83250906693043
k=377, max_dist=550.3376496506875, ev_in_k=87, 29.818661391361687
k=378, max_dist=550.3376496506875, ev_in_k=87, 29.69765908341576
k=379, max_dist=550.3376496506875, ev_in_k=87, 29.437850313221233
k=380, max_dist=550.3376496506875, ev_in_k=87, 29.430926475436863
k=381, max_dist=550.3376496506875, ev_in_k=87, 29.423013517969007
k=382, max_dist=550.3376496506875, ev_in_k=87, 29.262776129244973
k=383, max_dist=550.3376496506875, ev_in_k=87, 29.26211671612265
k=384, max_dist=550.3376496506875, ev_in_k=87, 29.223541048466863
k=385, max_dist=550.3376496506875, ev_in_k=87, 29.19221892515661
k=386, max_dist=515.3564914354159, ev_in_k=87, 29.181998021760634
k=387, max_dist=515.3564914354159, ev_in_k=87, 29.170787998681174
k=388, max_dist=515.3564914354159, ev_in_k=87, 29.170458292120014
k=389, max_dist=515.3564914354159, ev_in_k=87, 29.148697659083417
k=390, max_dist=515.3564914354159, ev_in_k=87, 29.14507088691065
k=391, max_dist=515.3564914354159, ev_in_k=87, 29.13847675568744
k=392, max_dist=515.3564914354159, ev_in_k=87, 29.136498516320476
k=393, max_dist=515.3564914354159, ev_in_k=87, 29.088361358391033
k=394, max_dist=515.3564914354159, ev_in_k=87, 28.980547312891527
k=395, max_dist=515.3564914354159, ev_in_k=87, 28.806132542037588
k=396, max_dist=515.3564914354159, ev_in_k=87, 28.79756017144741
k=397, max_dist=435.03671305870205, ev_in_k=87, 28.794592812396967
k=398, max_dist=435.03671305870205, ev_in_k=87, 28.740850642927793
k=399, max_dist=435.03671305870205, ev_in_k=87, 28.737553577316188
k=400, max_dist=435.03671305870205, ev_in_k=87, 28.734256511704583

KeyboardInterrupt: